name: Keep Render App Awake

on:
  schedule:
    # cada 13 minutos, 24 h al día (UTC)
    - cron: '*/13 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -fsS https://marosserver.onrender.com/contacts/all || exit 1
