name: Mantener vivo Maros Server

on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep-alive con reintento inmediato
        run: |
          curl --silent --fail "https://marosserver.onrender.com/contacts/all" \
            || curl --silent --fail "https://marosserver.onrender.com/contacts/all"
